name: animal_crossing_helper
description: Animal crossing helper.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  bot_toast: ^2.4.0
  cached_network_image: ^2.0.0
  dio: 3.0.8
  flare_flutter: ^2.0.1
  flutter_redux: 0.6.0
  html: ^0.14.0+3
  json_annotation: ^3.0.1
  pretty_dio_logger: 1.1.0
  redux_logging: 0.4.0
  redux_persist: ^0.8.3
  redux_persist_flutter: ^0.8.2
  redux_thunk: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.8.0
  json_serializable: ^3.2.5


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
   - assets/loading.flr
   - assets/butterfly.png
   - assets/fish.png
   - assets/pawprint.png
